name: paint_home
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  dio_interceptors: 0.0.5-nullsafety
  flutter_modular: ^5.0.2
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  equatable: 2.0.3
  connectivity_plus: ^2.3.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.otf
        - asset: assets/fonts/OpenSans-Light.otf
        - asset: assets/fonts/OpenSans-Medium.otf
        - asset: assets/fonts/OpenSans-Regular.otf
